[[redirects]]
from = "/proxy/*"
  to = "https://api.ohble.net/:splat"  
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[[redirects]]
from = "/prox/*"
  to = "https://api.ohble.net/v1/participant"  
  status = 200
  force = true







